<a href="https://colab.research.google.com/github/devjaime/data_science_escalab/blob/main/Copia_de_2021_11_16_Clase_04.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Pandas

PANel DAta
*   Libreria de código abierto
*   Proporciona herramientas de análisis y manipulación de datos de alto rendimiento

Pasos para procesamiento y análisis de datos
*   Cargar
*   Modelar
*   Analizar
*   Manipular
*   Preparar

DataFrame (df): estructura fundamental de Pandas
Estructura de datos etiquetados bidemensionales con columnas de tipos potencialmente diferentes, consta de 3 componenetes principales
*   Datos
*   Índice
*   Columnas

Especificar nombres de índices (filas) y columnas

NumPy alamcena como matrices

Pandas almacena como:

*   Series → 1D
*   DataFrame → 2D

Pandas cuenta con índices tanto en las filas como en las columnas. El dataframe puede mutar el tamaño y sus datos

Ventajas DataFrame

*   Rápido y eficiente, con indexación predeterminada y personalizada 
*   Herramientas para cargar datos desde diferentes formatos de archivos
*   Alineación de datos y manejo de datos faltantes
*   Remodelación y giro de conjunto de fechas
*   Etiquetado, corte, indexación de grandes conjuntos de datos
*   Las columnas se pueden eliminar o insertar
*   Agrupar por datos para agregación y transformaciones
*   Alto rendimiento de fusión y unión de datos
*   Funcionalidad de la serie de tiempo 



```
pip install pandas
import pandas as pd
```












In [ ]:
import pandas as pd
import numpy as np

In [ ]:
# df = pd.DataFrame(data=None, index: Optional[Axes]=None, columns: Optional[Axes]=None, dtype: Optional[Dtype]=None)
df = pd.DataFrame()
print(df)
print()
print(type(df))

Empty DataFrame
Columns: []
Index: []

<class 'pandas.core.frame.DataFrame'>


In [ ]:
df = pd.DataFrame(data=[[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(df)

   0   1   2   3
0  1   2   3   4
1  5   6   7   8
2  9  10  11  12


In [ ]:
df = pd.DataFrame([ [1,2,3],   [4,5,6],    [7,8,9]         ])
print(df)

   0  1  2
0  1  2  3
1  4  5  6
2  7  8  9


In [ ]:
df = pd.DataFrame(data=[[1,2,3,4],[5,6,7,8],[9,10,11,12]],\
                  index=["fila 1", "fila 2", "fila 3"])
print(df)

        0   1   2   3
fila 1  1   2   3   4
fila 2  5   6   7   8
fila 3  9  10  11  12


In [ ]:
df = pd.DataFrame(data=[[1,2,3,4],[5,6,7,8],[9,10,11,12]],\
                  index=["fila 1", "fila 2", "fila 3"],\
                  columns = ["a", "b", "c", "d"])
print(df)

        a   b   c   d
fila 1  1   2   3   4
fila 2  5   6   7   8
fila 3  9  10  11  12


In [ ]:
data = np.array([['','Col1','Col2'], ['Fila1',11,22], ['Fila2',33,44]])
print(data)

[['' 'Col1' 'Col2']
 ['Fila1' '11' '22']
 ['Fila2' '33' '44']]


In [ ]:
dataframe = pd.DataFrame(data = data[1:,1:], index = data[1:,0], columns = data[0,1:])
print(data[1:,1:])
print()
print(data[1:,0])
print()
print(data[0,1:])
print()
print(dataframe)

[['11' '22']
 ['33' '44']]

['Fila1' 'Fila2']

['Col1' 'Col2']

      Col1 Col2
Fila1   11   22
Fila2   33   44


In [ ]:
df_01 = pd.DataFrame([[1,2,3,4,5]])
print(df_01)

   0  1  2  3  4
0  1  2  3  4  5


In [ ]:
df_01 = pd.DataFrame([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]])
print(df_01)

    0   1   2   3   4
0   1   2   3   4   5
1   6   7   8   9  10
2  11  12  13  14  15


In [ ]:
df_01 = pd.DataFrame([1,2,3,4,5])
print(df_01)

   0
0  1
1  2
2  3
3  4
4  5


In [ ]:
serie = pd.Series({"Argentina":"Buenos Aires", "Chile":"Santiago de Chile", "Colombia":"Bogotá", "Perú":"Lima"})
print(serie)

Argentina         Buenos Aires
Chile        Santiago de Chile
Colombia                Bogotá
Perú                      Lima
dtype: object


In [ ]:
serie = pd.Series(["Argentina", "Chile", "Colombia", "Perú"])
print(serie)
print()
serie = pd.Series(["Buenos Aires", "Santiago de Chile", "Bogotá", "Lima"], ["Argentina", "Chile", "Colombia", "Perú"])
print(serie)

0    Argentina
1        Chile
2     Colombia
3         Perú
dtype: object

Argentina         Buenos Aires
Chile        Santiago de Chile
Colombia                Bogotá
Perú                      Lima
dtype: object


In [ ]:
# con datos faltantes
# NaN → np.nan
df_02 = pd.DataFrame([[1,2,3,4,5],[6,7,8,9],[11,12]])
print(df_02)

    0   1    2    3    4
0   1   2  3.0  4.0  5.0
1   6   7  8.0  9.0  NaN
2  11  12  NaN  NaN  NaN


In [ ]:
# con datos faltantes
df_02 = pd.DataFrame([[1,2,3,pd.NA,5],[6,7,8,9],[11,12]])
print(df_02)

# evitar el pd.NA pues no sirve después para algunas opercaciones matemáticas y funciones de pandas

    0   1    2     3    4
0   1   2  3.0  <NA>  5.0
1   6   7  8.0     9  NaN
2  11  12  NaN  None  NaN


Algunas veces cargando datos pueden aparecer NaN o None donde faltan datos

NaN es un valor númerico (float 64) y puede usarse para operaciones matemáticas

None es un tipo de dato de Python → indica que no existe o que es vacío, pero al usarlo como valor numerico sería un valor inválido 

In [ ]:
lista = [1, 2, 3, 4, None]
print(type(lista))

<class 'list'>


In [ ]:
serie_mala = pd.Series([1, 2, 3, 4, None])
print(serie_mala)
print(serie_mala.dtype)

print("\n\n*************\n")

serie_mala = pd.Series([1, 2, 3, 4, None], dtype=object)
print(serie_mala)
print(serie_mala.dtype)

0    1.0
1    2.0
2    3.0
3    4.0
4    NaN
dtype: float64
float64


*************

0       1
1       2
2       3
3       4
4    None
dtype: object
object


In [ ]:
serie_buena = pd.Series([1, 2, 3, 4, np.nan])
print(serie_buena)

print(serie_buena.dtype)

0    1.0
1    2.0
2    3.0
3    4.0
4    NaN
dtype: float64
float64


In [ ]:
v1 = np.nan
print(v1)
v2 = None
print(v2)

nan
None


In [ ]:
print(v1 + 2)

nan


In [ ]:
print(v2 + 2)

TypeError: ignored

In [ ]:
df = pd.DataFrame([[1,2,3],[4,5,6],[7,8,9],[10,11],[13,14,15]])
print(df)

    0   1     2
0   1   2   3.0
1   4   5   6.0
2   7   8   9.0
3  10  11   NaN
4  13  14  15.0


In [ ]:
print(df.interpolate())

    0   1     2
0   1   2   3.0
1   4   5   6.0
2   7   8   9.0
3  10  11  12.0
4  13  14  15.0


Como crear un DataFrame

df = pd.DataFrame([datos])

In [ ]:
df_01 = pd.DataFrame([1,2,3,4])
df_02 = pd.DataFrame([[1,2,3,4]])

df_03 = pd.DataFrame([[1,2,3,4],[5,6,7,8]])

print(df_01)
print()
print(df_02)
print()
print(df_03)

   0
0  1
1  2
2  3
3  4

   0  1  2  3
0  1  2  3  4

   0  1  2  3
0  1  2  3  4
1  5  6  7  8


In [ ]:
df_01 = pd.DataFrame((1,2,3,4))
df_02 = pd.DataFrame(((1,2,3,4)))

df_03 = pd.DataFrame(((1,2,3,4),(5,6,7,8)))
df_04 = pd.DataFrame([(1,2,3,4),(5,6,7,8)])
df_05 = pd.DataFrame(([1,2,3,4],(5,6,7,8)))

print(df_01)
print()
print(df_02)
print()
print(df_03)
print()
print(df_04)
print()
print(df_05)

   0
0  1
1  2
2  3
3  4

   0
0  1
1  2
2  3
3  4

   0  1  2  3
0  1  2  3  4
1  5  6  7  8

   0  1  2  3
0  1  2  3  4
1  5  6  7  8

   0  1  2  3
0  1  2  3  4
1  5  6  7  8


## Estadísticas del DataFrame

In [ ]:
df = pd.DataFrame([[1,2,3],[4,5,6],[7,8,9]])
print(df)

   0  1  2
0  1  2  3
1  4  5  6
2  7  8  9


In [ ]:
# Media de las columnas del DataFrame
print(df.mean())

0    4.0
1    5.0
2    6.0
dtype: float64


In [ ]:
# Correlación entre las columnas del DataFrame
# https://www.it-swarm-es.com/es/python/usa-.corr-para-obtener-la-correlacion-entre-dos-columnas/829778664/
print(df.corr())

     0    1    2
0  1.0  1.0  1.0
1  1.0  1.0  1.0
2  1.0  1.0  1.0


In [ ]:
# Conteo de datos (no nulos) de las columnas del DataFrame
print(df.count())

0    3
1    3
2    3
dtype: int64


In [ ]:
df_nulo = pd.DataFrame([[1,2],[4,5,6],[7,8,9]])
print(df_nulo)
print()
print(df_nulo.count())

   0  1    2
0  1  2  NaN
1  4  5  6.0
2  7  8  9.0

0    3
1    3
2    2
dtype: int64


In [ ]:
# Máximo y mínimo de cada columna del DataFrame
print(df.max())
print()
print(df.min())

0    7
1    8
2    9
dtype: int64

0    1
1    2
2    3
dtype: int64


In [ ]:
# Mediana de cada columna del DataFrame
print(df.median())

0    4.0
1    5.0
2    6.0
dtype: float64


In [ ]:
# Desviación estándar de cada columna del DataFrame
print(df.std())

0    3.0
1    3.0
2    3.0
dtype: float64


In [ ]:
# Estadísticas del DataFrame
print(df.describe())

         0    1    2
count  3.0  3.0  3.0
mean   4.0  5.0  6.0
std    3.0  3.0  3.0
min    1.0  2.0  3.0
25%    2.5  3.5  4.5
50%    4.0  5.0  6.0
75%    5.5  6.5  7.5
max    7.0  8.0  9.0


## Cómo seleccionar un índice o una columna del DataFrame

In [ ]:
arreglo = np.arange(25).reshape([5,5])+1
print(arreglo)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [ ]:
df = pd.DataFrame(arreglo)
print(df)

    0   1   2   3   4
0   1   2   3   4   5
1   6   7   8   9  10
2  11  12  13  14  15
3  16  17  18  19  20
4  21  22  23  24  25


In [ ]:
# Primera columna del DataFrame
print(df[0])

0     1
1     6
2    11
3    16
4    21
Name: 0, dtype: int64


In [ ]:
# Más de una columna y generar un nuevo DataFrame
df_nuevo = df[[0,2]]
print(df_nuevo)

    0   2
0   1   3
1   6   8
2  11  13
3  16  18
4  21  23


In [ ]:
# Seleccionar el valor de la primera fila y cuarta columna del DataFrame
print(df.iloc[0][3])

4


In [ ]:
# Seleccionar los valores de la primera fila del DataFrame
print(df.loc[0])

0    1
1    2
2    3
3    4
4    5
Name: 0, dtype: int64


In [ ]:
# Seleccionar los valores de la tercer fila del DataFrame
print(df.iloc[2,:])

0    11
1    12
2    13
3    14
4    15
Name: 2, dtype: int64


In [ ]:
# Seleccionar los valores de la primera columna del DataFrame
print(df.iloc[:,0])

0     1
1     6
2    11
3    16
4    21
Name: 0, dtype: int64


## Importar y exportar datos

*   Abrir un archivo local (csv, xml)
*   Abrir un archivo de manera remota desde un sitio web a través de una URL

pd.read_tipoarchivo()

→ *tipo de archivo, verificar en la documentación*

https://pandas.pydata.org/docs/reference/io.html


```
df = pd.read_csv('datos.csv')
```


pd.to_tipoarchivo()

→ *tipo de archivo, verificar en la documentación*

```
df = pd.to_csv('datos_modificados.csv')
```



In [ ]:
url="https://raw.githubusercontent.com/cs109/2014_data/master/countries.csv"
df_urlc=pd.read_csv(url)

In [ ]:
print(df_urlc)

       Country         Region
0      Algeria         AFRICA
1       Angola         AFRICA
2        Benin         AFRICA
3     Botswana         AFRICA
4      Burkina         AFRICA
..         ...            ...
189   Paraguay  SOUTH AMERICA
190       Peru  SOUTH AMERICA
191   Suriname  SOUTH AMERICA
192    Uruguay  SOUTH AMERICA
193  Venezuela  SOUTH AMERICA

[194 rows x 2 columns]


In [ ]:
arreglo = np.arange(100).reshape([20,5])+1
print(arreglo)

[[  1   2   3   4   5]
 [  6   7   8   9  10]
 [ 11  12  13  14  15]
 [ 16  17  18  19  20]
 [ 21  22  23  24  25]
 [ 26  27  28  29  30]
 [ 31  32  33  34  35]
 [ 36  37  38  39  40]
 [ 41  42  43  44  45]
 [ 46  47  48  49  50]
 [ 51  52  53  54  55]
 [ 56  57  58  59  60]
 [ 61  62  63  64  65]
 [ 66  67  68  69  70]
 [ 71  72  73  74  75]
 [ 76  77  78  79  80]
 [ 81  82  83  84  85]
 [ 86  87  88  89  90]
 [ 91  92  93  94  95]
 [ 96  97  98  99 100]]


In [ ]:
arreglo[3,2] = np.nan
print(arreglo)

ValueError: ignored

In [ ]:
arreglo = np.arange(100, dtype=float).reshape([20,5])+1
print(arreglo)

[[  1.   2.   3.   4.   5.]
 [  6.   7.   8.   9.  10.]
 [ 11.  12.  13.  14.  15.]
 [ 16.  17.  18.  19.  20.]
 [ 21.  22.  23.  24.  25.]
 [ 26.  27.  28.  29.  30.]
 [ 31.  32.  33.  34.  35.]
 [ 36.  37.  38.  39.  40.]
 [ 41.  42.  43.  44.  45.]
 [ 46.  47.  48.  49.  50.]
 [ 51.  52.  53.  54.  55.]
 [ 56.  57.  58.  59.  60.]
 [ 61.  62.  63.  64.  65.]
 [ 66.  67.  68.  69.  70.]
 [ 71.  72.  73.  74.  75.]
 [ 76.  77.  78.  79.  80.]
 [ 81.  82.  83.  84.  85.]
 [ 86.  87.  88.  89.  90.]
 [ 91.  92.  93.  94.  95.]
 [ 96.  97.  98.  99. 100.]]


In [ ]:
arreglo[2,2] = np.nan
arreglo[6,2] = np.nan
arreglo[10,2] = np.nan
arreglo[16,2] = np.nan

arreglo[5,3] = np.nan
arreglo[8,3] = np.nan
print(arreglo)

[[  1.   2.   3.   4.   5.]
 [  6.   7.   8.   9.  10.]
 [ 11.  12.  nan  14.  15.]
 [ 16.  17.  18.  19.  20.]
 [ 21.  22.  23.  24.  25.]
 [ 26.  27.  28.  nan  30.]
 [ 31.  32.  nan  34.  35.]
 [ 36.  37.  38.  39.  40.]
 [ 41.  42.  43.  nan  45.]
 [ 46.  47.  48.  49.  50.]
 [ 51.  52.  nan  54.  55.]
 [ 56.  57.  58.  59.  60.]
 [ 61.  62.  63.  64.  65.]
 [ 66.  67.  68.  69.  70.]
 [ 71.  72.  73.  74.  75.]
 [ 76.  77.  78.  79.  80.]
 [ 81.  82.  nan  84.  85.]
 [ 86.  87.  88.  89.  90.]
 [ 91.  92.  93.  94.  95.]
 [ 96.  97.  98.  99. 100.]]


In [ ]:
df = pd.DataFrame(arreglo)
print(df)

       0     1     2     3      4
0    1.0   2.0   3.0   4.0    5.0
1    6.0   7.0   8.0   9.0   10.0
2   11.0  12.0   NaN  14.0   15.0
3   16.0  17.0  18.0  19.0   20.0
4   21.0  22.0  23.0  24.0   25.0
5   26.0  27.0  28.0   NaN   30.0
6   31.0  32.0   NaN  34.0   35.0
7   36.0  37.0  38.0  39.0   40.0
8   41.0  42.0  43.0   NaN   45.0
9   46.0  47.0  48.0  49.0   50.0
10  51.0  52.0   NaN  54.0   55.0
11  56.0  57.0  58.0  59.0   60.0
12  61.0  62.0  63.0  64.0   65.0
13  66.0  67.0  68.0  69.0   70.0
14  71.0  72.0  73.0  74.0   75.0
15  76.0  77.0  78.0  79.0   80.0
16  81.0  82.0   NaN  84.0   85.0
17  86.0  87.0  88.0  89.0   90.0
18  91.0  92.0  93.0  94.0   95.0
19  96.0  97.0  98.0  99.0  100.0


In [ ]:
# Datos nulos en el DataFrame
print(df.isnull())

        0      1      2      3      4
0   False  False  False  False  False
1   False  False  False  False  False
2   False  False   True  False  False
3   False  False  False  False  False
4   False  False  False  False  False
5   False  False  False   True  False
6   False  False   True  False  False
7   False  False  False  False  False
8   False  False  False   True  False
9   False  False  False  False  False
10  False  False   True  False  False
11  False  False  False  False  False
12  False  False  False  False  False
13  False  False  False  False  False
14  False  False  False  False  False
15  False  False  False  False  False
16  False  False   True  False  False
17  False  False  False  False  False
18  False  False  False  False  False
19  False  False  False  False  False


In [ ]:
# Suma datos nulos en el DataFrame
print(df.isnull().sum())

0    0
1    0
2    4
3    2
4    0
dtype: int64


Podemos eliminar las filas o las columnas de los datos faltantes

filas → pd.dropna()

columnas → pd.dropna(axis = 1)

In [ ]:
# Eliminar las filas
print(df.dropna())

       0     1     2     3      4
0    1.0   2.0   3.0   4.0    5.0
1    6.0   7.0   8.0   9.0   10.0
3   16.0  17.0  18.0  19.0   20.0
4   21.0  22.0  23.0  24.0   25.0
7   36.0  37.0  38.0  39.0   40.0
9   46.0  47.0  48.0  49.0   50.0
11  56.0  57.0  58.0  59.0   60.0
12  61.0  62.0  63.0  64.0   65.0
13  66.0  67.0  68.0  69.0   70.0
14  71.0  72.0  73.0  74.0   75.0
15  76.0  77.0  78.0  79.0   80.0
17  86.0  87.0  88.0  89.0   90.0
18  91.0  92.0  93.0  94.0   95.0
19  96.0  97.0  98.0  99.0  100.0


In [ ]:
# Eliminar las columnas
print(df.dropna(axis = 1))

       0     1      4
0    1.0   2.0    5.0
1    6.0   7.0   10.0
2   11.0  12.0   15.0
3   16.0  17.0   20.0
4   21.0  22.0   25.0
5   26.0  27.0   30.0
6   31.0  32.0   35.0
7   36.0  37.0   40.0
8   41.0  42.0   45.0
9   46.0  47.0   50.0
10  51.0  52.0   55.0
11  56.0  57.0   60.0
12  61.0  62.0   65.0
13  66.0  67.0   70.0
14  71.0  72.0   75.0
15  76.0  77.0   80.0
16  81.0  82.0   85.0
17  86.0  87.0   90.0
18  91.0  92.0   95.0
19  96.0  97.0  100.0


In [ ]:
# si no se salva se mantiene como el original o el último cambio que fue salvado
print(df)

       0     1     2     3      4
0    1.0   2.0   3.0   4.0    5.0
1    6.0   7.0   8.0   9.0   10.0
2   11.0  12.0   NaN  14.0   15.0
3   16.0  17.0  18.0  19.0   20.0
4   21.0  22.0  23.0  24.0   25.0
5   26.0  27.0  28.0   NaN   30.0
6   31.0  32.0   NaN  34.0   35.0
7   36.0  37.0  38.0  39.0   40.0
8   41.0  42.0  43.0   NaN   45.0
9   46.0  47.0  48.0  49.0   50.0
10  51.0  52.0   NaN  54.0   55.0
11  56.0  57.0  58.0  59.0   60.0
12  61.0  62.0  63.0  64.0   65.0
13  66.0  67.0  68.0  69.0   70.0
14  71.0  72.0  73.0  74.0   75.0
15  76.0  77.0  78.0  79.0   80.0
16  81.0  82.0   NaN  84.0   85.0
17  86.0  87.0  88.0  89.0   90.0
18  91.0  92.0  93.0  94.0   95.0
19  96.0  97.0  98.0  99.0  100.0


In [ ]:
# se puede rellenar los datos faltantes
print(df.fillna(99))

       0     1     2     3      4
0    1.0   2.0   3.0   4.0    5.0
1    6.0   7.0   8.0   9.0   10.0
2   11.0  12.0  99.0  14.0   15.0
3   16.0  17.0  18.0  19.0   20.0
4   21.0  22.0  23.0  24.0   25.0
5   26.0  27.0  28.0  99.0   30.0
6   31.0  32.0  99.0  34.0   35.0
7   36.0  37.0  38.0  39.0   40.0
8   41.0  42.0  43.0  99.0   45.0
9   46.0  47.0  48.0  49.0   50.0
10  51.0  52.0  99.0  54.0   55.0
11  56.0  57.0  58.0  59.0   60.0
12  61.0  62.0  63.0  64.0   65.0
13  66.0  67.0  68.0  69.0   70.0
14  71.0  72.0  73.0  74.0   75.0
15  76.0  77.0  78.0  79.0   80.0
16  81.0  82.0  99.0  84.0   85.0
17  86.0  87.0  88.0  89.0   90.0
18  91.0  92.0  93.0  94.0   95.0
19  96.0  97.0  98.0  99.0  100.0


In [ ]:
# se puede rellenar los datos faltantes
print(df.fillna(df.mean()))

       0     1      2          3      4
0    1.0   2.0   3.00   4.000000    5.0
1    6.0   7.0   8.00   9.000000   10.0
2   11.0  12.0  51.75  14.000000   15.0
3   16.0  17.0  18.00  19.000000   20.0
4   21.0  22.0  23.00  24.000000   25.0
5   26.0  27.0  28.00  53.166667   30.0
6   31.0  32.0  51.75  34.000000   35.0
7   36.0  37.0  38.00  39.000000   40.0
8   41.0  42.0  43.00  53.166667   45.0
9   46.0  47.0  48.00  49.000000   50.0
10  51.0  52.0  51.75  54.000000   55.0
11  56.0  57.0  58.00  59.000000   60.0
12  61.0  62.0  63.00  64.000000   65.0
13  66.0  67.0  68.00  69.000000   70.0
14  71.0  72.0  73.00  74.000000   75.0
15  76.0  77.0  78.00  79.000000   80.0
16  81.0  82.0  51.75  84.000000   85.0
17  86.0  87.0  88.00  89.000000   90.0
18  91.0  92.0  93.00  94.000000   95.0
19  96.0  97.0  98.00  99.000000  100.0


In [ ]:
# se puede rellenar los datos faltantes
print(df.interpolate())

       0     1     2     3      4
0    1.0   2.0   3.0   4.0    5.0
1    6.0   7.0   8.0   9.0   10.0
2   11.0  12.0  13.0  14.0   15.0
3   16.0  17.0  18.0  19.0   20.0
4   21.0  22.0  23.0  24.0   25.0
5   26.0  27.0  28.0  29.0   30.0
6   31.0  32.0  33.0  34.0   35.0
7   36.0  37.0  38.0  39.0   40.0
8   41.0  42.0  43.0  44.0   45.0
9   46.0  47.0  48.0  49.0   50.0
10  51.0  52.0  53.0  54.0   55.0
11  56.0  57.0  58.0  59.0   60.0
12  61.0  62.0  63.0  64.0   65.0
13  66.0  67.0  68.0  69.0   70.0
14  71.0  72.0  73.0  74.0   75.0
15  76.0  77.0  78.0  79.0   80.0
16  81.0  82.0  83.0  84.0   85.0
17  86.0  87.0  88.0  89.0   90.0
18  91.0  92.0  93.0  94.0   95.0
19  96.0  97.0  98.0  99.0  100.0


# Generación de datos aleatórios

## Nombres

In [ ]:
!pip install names

In [ ]:
import names

In [ ]:
print(names.get_full_name())
print(names.get_full_name(gender='male'))
print(names.get_first_name())
print(names.get_first_name(gender='female'))
print(names.get_last_name())

Ron Holland
Jonas Wiley
Carmen
Ashley
Gutierrez


In [ ]:
for i in range(5):
  print(names.get_full_name())

Brett Owens
Rosa Donahue
Leona Bell
Joseph Rogers
Chad Roddy


## Fechas

https://stackoverflow.com/questions/553303/generate-a-random-date-between-two-other-dates

In [ ]:
!pip install faker

In [ ]:
from faker import Faker

In [ ]:
fake = Faker()

print(fake.date_between(start_date='today', end_date='+30y'))
print(fake.date_time_between(start_date='-30y', end_date='now'))

import datetime
start_date = datetime.date(year=2015, month=1, day=1)
print(fake.date_between(start_date=start_date, end_date='+30y'))

2030-02-17
1996-04-25 15:06:01
2031-03-31


In [ ]:
for i in range(5):
  print(fake.date_between(start_date='-50y', end_date='-30y'))

1971-11-28
1983-11-07
1974-01-26
1982-02-18
1980-09-06


## Números

In [ ]:
import random

In [ ]:
print(random.random())
print(random.randint(20,90))
print(random.randrange(10,20,2))
print(random.uniform(10,20))
print(random.choice([5,8,9]))
print(random.choice([True, False]))

0.5201139172715541
33
12
19.69296041626155
9
True


In [ ]:
for i in range(5):
  print(random.randint(20,90))

60
79
72
34
40


## Otros

In [ ]:
!pip install pycountry

In [ ]:
import pycountry

In [ ]:
print(len(pycountry.countries))

249


In [ ]:
print(list(pycountry.countries)[50])

Country(alpha_2='KM', alpha_3='COM', name='Comoros', numeric='174', official_name='Union of the Comoros')


In [ ]:
print(list(pycountry.countries)[random.randint(0,len(pycountry.countries))])

Country(alpha_2='TR', alpha_3='TUR', name='Turkey', numeric='792', official_name='Republic of Turkey')


In [ ]:
pais = list(pycountry.countries)[random.randint(0,len(pycountry.countries))]
print(pais)
print(pais.name)

Country(alpha_2='PT', alpha_3='PRT', name='Portugal', numeric='620', official_name='Portuguese Republic')
Portugal


In [ ]:
for i in range(5):
  print(list(pycountry.countries)[random.randint(0,len(pycountry.countries))].name)

Mauritius
Ethiopia
Brazil
Samoa
Greece


## Función para crear un dato aleatoriamente

In [ ]:
def generar_registro():
  if random.choice([True,False]):
    nombre = names.get_first_name(gender='male')
    sexo = "masculino"
  else:
    nombre = names.get_first_name(gender='female')
    sexo = "femenino"
  
  apellido = names.get_last_name()

  fecha_nacimiento = fake.date_between(start_date='-50y', end_date='-30y')

  id = random.randint(1000000,9999999)

  dato_01 = random.randint(0,1000)
  dato_02 = random.randint(0,1000)
  dato_03 = random.uniform(0,1000)
  dato_04 = random.uniform(0,1000)

  probabilidad_error = 0.1

  # if random.random() < probabilidad_error: id = np.nan
  if random.random() < probabilidad_error: nombre = "???"
  if random.random() < probabilidad_error: apellido = np.nan
  if random.random() < probabilidad_error: sexo = np.nan
  if random.random() < probabilidad_error: fecha_nacimiento = np.nan
  if random.random() < probabilidad_error: dato_01 = np.nan
  if random.random() < probabilidad_error: dato_02 = np.nan
  if random.random() < probabilidad_error: dato_03 = np.nan
  if random.random() < probabilidad_error: dato_04 = np.nan
 
  


  return id, nombre, apellido, sexo, fecha_nacimiento, dato_01, dato_02, dato_03, dato_04




In [ ]:
generar_registro()

(3805775,
 'Ben',
 'Davis',
 nan,
 datetime.date(1987, 5, 20),
 61,
 650,
 nan,
 622.3581138828695)

In [ ]:
for i in range(20):
  lista = generar_registro()
  print(lista)

(8073002, '???', 'Hanes', nan, datetime.date(1981, 1, 21), 132, 800, 378.81141514906346, 871.5183593186641)
(9256349, 'Mary', 'Morris', 'femenino', datetime.date(1981, 2, 7), 429, 120, 180.11884442345294, 644.4468958681618)
(3038091, 'Charles', 'Transue', 'masculino', nan, 690, 90, 820.5383832738718, 581.7280787747644)
(8581504, 'Frederick', 'Lorenzen', 'masculino', datetime.date(1979, 4, 18), 37, 322, 432.96629191052574, 658.87667658735)
(1597244, 'Beverly', 'Curry', nan, datetime.date(1982, 4, 22), 570, 387, 728.7259649388234, 155.0240369425766)
(6717094, 'Pamela', 'Vaughn', 'femenino', datetime.date(1990, 6, 13), 153, 363, 74.78181126877936, 974.5940326853649)
(1483162, 'Elnora', 'Peel', 'femenino', datetime.date(1985, 8, 14), 587, 781, 29.188518789252882, 369.9493739364117)
(4015940, 'Marcella', 'Drew', 'femenino', nan, nan, 254, 710.6000692819418, 645.7568386245124)
(5412609, 'Shannon', 'Wilbanks', 'femenino', datetime.date(1972, 6, 8), 833, nan, 261.5007767961346, 707.99526805755

In [ ]:
dataframe_nombres = pd.DataFrame(columns=["id", "nombre", "apellido", "sexo", "fecha de nacimiento", "dato 01", "dato 02", "dato 03", "dato 04"])

print(dataframe_nombres)


Empty DataFrame
Columns: [id, nombre, apellido, sexo, fecha de nacimiento, dato 01, dato 02, dato 03, dato 04]
Index: []


In [ ]:
dataframe_nombres = pd.DataFrame(columns=["id", "nombre", "apellido", "sexo", "fecha de nacimiento", "dato 01", "dato 02", "dato 03", "dato 04"])

for i in range(50):
  id, nombre, apellido, sexo, fecha_nacimiento, dato_01, dato_02, dato_03, dato_04 = generar_registro()
  dato_nuevo = {"id": id,
        "nombre": nombre,
        "apellido": apellido,
        "sexo": sexo,
        "fecha de nacimiento": fecha_nacimiento,
        "dato 01": dato_01,
        "dato 02": dato_02,
        "dato 03": dato_03,
        "dato 04": dato_04
  }

  dataframe_nombres = dataframe_nombres.append(dato_nuevo, ignore_index=True)


# guardar el DataFrame como csv
dataframe_nombres.to_csv('mi_archivo_csv.csv', index=False)

In [ ]:
dataframe_nombres.to_csv('mi_archivo_csv_1.csv', index=True)

In [ ]:
print(dataframe_nombres)

         id     nombre   apellido  ... dato 02     dato 03     dato 04
0   4292166      Glenn   Hubertus  ...     666         NaN    8.348096
1   4660687      Jesse    Andrews  ...     678  531.908726         NaN
2   2083836     Harold    Maulden  ...     940  634.372023  774.595716
3   8070304    Darrick     Graham  ...     176  181.339371  419.969781
4   2664601   Madeline      Corns  ...     NaN  405.608945         NaN
5   2312309      James  Mcfarland  ...     795  275.142805  873.447967
6   5090841        ???        NaN  ...     139  791.892719  475.066515
7   5055108       Jeff      Piper  ...     392  327.593104  976.313296
8   4222113        Max    Allegra  ...     385  268.400996  265.210264
9   5428583       Mimi    Maxwell  ...     243  157.481774  426.939683
10  1007469      Wanda       Burt  ...     504  709.203480  578.718582
11  6497735    Crystal    Lavelle  ...     813  444.283423  866.470594
12  2479885     Judith        NaN  ...     176  146.491995  548.467254
13  27

In [ ]:
data = pd.read_csv('mi_archivo_csv.csv')
print(data)

         id     nombre   apellido  ... dato 02     dato 03     dato 04
0   4292166      Glenn   Hubertus  ...   666.0         NaN    8.348096
1   4660687      Jesse    Andrews  ...   678.0  531.908726         NaN
2   2083836     Harold    Maulden  ...   940.0  634.372023  774.595716
3   8070304    Darrick     Graham  ...   176.0  181.339371  419.969781
4   2664601   Madeline      Corns  ...     NaN  405.608945         NaN
5   2312309      James  Mcfarland  ...   795.0  275.142805  873.447967
6   5090841        ???        NaN  ...   139.0  791.892719  475.066515
7   5055108       Jeff      Piper  ...   392.0  327.593104  976.313296
8   4222113        Max    Allegra  ...   385.0  268.400996  265.210264
9   5428583       Mimi    Maxwell  ...   243.0  157.481774  426.939683
10  1007469      Wanda       Burt  ...   504.0  709.203480  578.718582
11  6497735    Crystal    Lavelle  ...   813.0  444.283423  866.470594
12  2479885     Judith        NaN  ...   176.0  146.491995  548.467254
13  27

In [ ]:
data = pd.read_csv('mi_archivo_csv.csv', index_col="id")
print(data)

            nombre   apellido       sexo  ... dato 02     dato 03     dato 04
id                                        ...                                
4292166      Glenn   Hubertus  masculino  ...   666.0         NaN    8.348096
4660687      Jesse    Andrews  masculino  ...   678.0  531.908726         NaN
2083836     Harold    Maulden  masculino  ...   940.0  634.372023  774.595716
8070304    Darrick     Graham  masculino  ...   176.0  181.339371  419.969781
2664601   Madeline      Corns   femenino  ...     NaN  405.608945         NaN
2312309      James  Mcfarland  masculino  ...   795.0  275.142805  873.447967
5090841        ???        NaN  masculino  ...   139.0  791.892719  475.066515
5055108       Jeff      Piper  masculino  ...   392.0  327.593104  976.313296
4222113        Max    Allegra  masculino  ...   385.0  268.400996  265.210264
5428583       Mimi    Maxwell   femenino  ...   243.0  157.481774  426.939683
1007469      Wanda       Burt   femenino  ...   504.0  709.20348

In [ ]:
data = pd.read_csv(
    'mi_archivo_csv.csv',      # camino del archivo csv
    dtype={"id": str},             # pasar los datos de la columna id como float
    na_values=['.', '???']       # tomar cualquier '.' o '???' como valores NA
)
print(data)

         id     nombre   apellido  ... dato 02     dato 03     dato 04
0   4292166      Glenn   Hubertus  ...   666.0         NaN    8.348096
1   4660687      Jesse    Andrews  ...   678.0  531.908726         NaN
2   2083836     Harold    Maulden  ...   940.0  634.372023  774.595716
3   8070304    Darrick     Graham  ...   176.0  181.339371  419.969781
4   2664601   Madeline      Corns  ...     NaN  405.608945         NaN
5   2312309      James  Mcfarland  ...   795.0  275.142805  873.447967
6   5090841        NaN        NaN  ...   139.0  791.892719  475.066515
7   5055108       Jeff      Piper  ...   392.0  327.593104  976.313296
8   4222113        Max    Allegra  ...   385.0  268.400996  265.210264
9   5428583       Mimi    Maxwell  ...   243.0  157.481774  426.939683
10  1007469      Wanda       Burt  ...   504.0  709.203480  578.718582
11  6497735    Crystal    Lavelle  ...   813.0  444.283423  866.470594
12  2479885     Judith        NaN  ...   176.0  146.491995  548.467254
13  27

In [ ]:
data = pd.read_csv(
    'mi_archivo_csv.csv',      # camino del archivo csv
    sep=',',                    # separación de columnas
    quotechar="'",        # comillas simples permitidas como carácter de comillas
    dtype={"id": float},             # pasar los datos de la columna id como float
    #usecols=['id', 'nombre', 'dato 04', "fecha de nacimiento"],   # cargar solamente las columnas indicadas
    #parse_dates=['fecha de nacimiento'],     # Intepret the birth_date column as a date
    skiprows=10,        # saltar las primeras 10 filas
    na_values=['.', '???']       # tomar cualquier '.' o '???' como valores NA
)


In [ ]:
# primeras filas
data = pd.read_csv('mi_archivo_csv.csv')
print(data.head(8))

        id    nombre   apellido  ... dato 02     dato 03     dato 04
0  4292166     Glenn   Hubertus  ...   666.0         NaN    8.348096
1  4660687     Jesse    Andrews  ...   678.0  531.908726         NaN
2  2083836    Harold    Maulden  ...   940.0  634.372023  774.595716
3  8070304   Darrick     Graham  ...   176.0  181.339371  419.969781
4  2664601  Madeline      Corns  ...     NaN  405.608945         NaN
5  2312309     James  Mcfarland  ...   795.0  275.142805  873.447967
6  5090841       ???        NaN  ...   139.0  791.892719  475.066515
7  5055108      Jeff      Piper  ...   392.0  327.593104  976.313296

[8 rows x 9 columns]


In [ ]:
# últimas filas
data = pd.read_csv('mi_archivo_csv.csv')
print(data.tail(8))

         id  nombre   apellido  ... dato 02     dato 03     dato 04
42  3819168    Kris  Armstrong  ...   105.0  664.534002  143.061001
43  5018014  Thomas     Tongue  ...   145.0  976.394745  809.289486
44  2076649    Lara      Soucy  ...     NaN  455.914487  701.041567
45  4297762  Harold     Howard  ...   173.0  965.993949  751.407470
46  6667462   Mario       Tate  ...   381.0  186.256052  169.403874
47  9112214   Leila    Fuentes  ...   394.0  786.760581  571.549874
48  9035777   Katie     Hardin  ...   179.0         NaN  404.242245
49  9479397  Brenda     Arnold  ...   447.0         NaN  934.527206

[8 rows x 9 columns]


In [ ]:
print(data.describe())

          dato 01     dato 02     dato 03     dato 04
count   42.000000   47.000000   47.000000   45.000000
mean   544.261905  462.297872  466.345658  501.820282
std    255.366123  278.001245  319.650496  283.435805
min     11.000000   29.000000   14.003894    7.133942
25%    399.250000  190.500000  179.591208  265.210264
50%    561.000000  425.000000  405.608945  475.066515
75%    712.750000  672.000000  741.951043  752.771586
max    998.000000  980.000000  993.932350  976.313296


In [ ]:
# filtrar
data = pd.read_csv('mi_archivo_csv.csv')
data_filtrado = data.dropna()
print(data_filtrado)


         id     nombre   apellido  ... dato 02     dato 03     dato 04
2   2083836     Harold    Maulden  ...   940.0  634.372023  774.595716
5   2312309      James  Mcfarland  ...   795.0  275.142805  873.447967
7   5055108       Jeff      Piper  ...   392.0  327.593104  976.313296
9   5428583       Mimi    Maxwell  ...   243.0  157.481774  426.939683
11  6497735    Crystal    Lavelle  ...   813.0  444.283423  866.470594
14  9348656        ???     Fricke  ...   369.0  171.569390  120.983420
17  7267886     Dwight     Albino  ...   641.0  192.767701  402.148325
18  9010043     Eugene     Orozco  ...    83.0  102.453252  120.386433
19  6120269      Casey     Watson  ...   607.0   34.027543  114.493141
20  9541242      Diane    Grenier  ...   542.0  446.349352  414.963482
21  5880168       Alex      Hicks  ...   951.0  177.843045  921.834868
23  6094234      Alice       Kane  ...   812.0  336.236790  480.610693
27  1272526    Harriet     Reilly  ...   745.0  926.932778  521.791550
30  73

In [ ]:
# rellenar
data = pd.read_csv('mi_archivo_csv.csv')
data_nuevo = data.fillna(0)
print(data_nuevo)

         id     nombre   apellido  ... dato 02     dato 03     dato 04
0   4292166      Glenn   Hubertus  ...   666.0    0.000000    8.348096
1   4660687      Jesse    Andrews  ...   678.0  531.908726    0.000000
2   2083836     Harold    Maulden  ...   940.0  634.372023  774.595716
3   8070304    Darrick     Graham  ...   176.0  181.339371  419.969781
4   2664601   Madeline      Corns  ...     0.0  405.608945    0.000000
5   2312309      James  Mcfarland  ...   795.0  275.142805  873.447967
6   5090841        ???          0  ...   139.0  791.892719  475.066515
7   5055108       Jeff      Piper  ...   392.0  327.593104  976.313296
8   4222113        Max    Allegra  ...   385.0  268.400996  265.210264
9   5428583       Mimi    Maxwell  ...   243.0  157.481774  426.939683
10  1007469      Wanda       Burt  ...   504.0  709.203480  578.718582
11  6497735    Crystal    Lavelle  ...   813.0  444.283423  866.470594
12  2479885     Judith          0  ...   176.0  146.491995  548.467254
13  27

In [ ]:
# rellenar
data = pd.read_csv('mi_archivo_csv.csv')
data_nuevo = data.fillna({"dato 01": 1111, "dato 02": 2222, "dato 03": 3333, "dato 04": 4444, "apellido":"apellido no registrado"})
print(data_nuevo)

         id     nombre  ...      dato 03      dato 04
0   4292166      Glenn  ...  3333.000000     8.348096
1   4660687      Jesse  ...   531.908726  4444.000000
2   2083836     Harold  ...   634.372023   774.595716
3   8070304    Darrick  ...   181.339371   419.969781
4   2664601   Madeline  ...   405.608945  4444.000000
5   2312309      James  ...   275.142805   873.447967
6   5090841        ???  ...   791.892719   475.066515
7   5055108       Jeff  ...   327.593104   976.313296
8   4222113        Max  ...   268.400996   265.210264
9   5428583       Mimi  ...   157.481774   426.939683
10  1007469      Wanda  ...   709.203480   578.718582
11  6497735    Crystal  ...   444.283423   866.470594
12  2479885     Judith  ...   146.491995   548.467254
13  2786655       Mary  ...   679.721783   894.378825
14  9348656        ???  ...   171.569390   120.983420
15  1945735    Stanley  ...    95.919213  4444.000000
16  6910445     Robert  ...   684.884157   781.899476
17  7267886     Dwight  ... 

In [ ]:
data["dato 01"]>800

0     False
1     False
2     False
3     False
4      True
5      True
6     False
7      True
8     False
9     False
10    False
11    False
12    False
13    False
14    False
15    False
16    False
17    False
18     True
19    False
20    False
21    False
22    False
23    False
24    False
25    False
26    False
27    False
28    False
29     True
30    False
31    False
32    False
33    False
34    False
35    False
36    False
37     True
38    False
39    False
40    False
41    False
42     True
43    False
44    False
45    False
46    False
47    False
48    False
49     True
Name: dato 01, dtype: bool

In [ ]:
dato_02 = data[data["dato 03"]>800]
print(dato_02)

         id     nombre  apellido  ... dato 02     dato 03     dato 04
22  5217160     Harold  Metivier  ...    29.0  938.937514  779.415939
24  9695376   Danielle   Simpson  ...   137.0  918.232060  371.214999
25  4849092  Catherine     Green  ...     NaN  993.932350  471.824089
27  1272526    Harriet    Reilly  ...   745.0  926.932778  521.791550
34  1789947        ???  Anderson  ...   554.0  941.033761    7.133942
38  9328845     Trisha     Hague  ...   802.0  837.335328  752.771586
40  2821714    Richard    Howard  ...   815.0  969.838392  297.443130
43  5018014     Thomas    Tongue  ...   145.0  976.394745  809.289486
45  4297762     Harold    Howard  ...   173.0  965.993949  751.407470

[9 rows x 9 columns]


In [ ]:
# dato_02 = data[data["dato 01"]>800 and data["dato 04"]>700]
# and → &
# or → |
dato_02 = data[(data["dato 03"]>800) & (data["dato 04"]>700)]
print(dato_02)

         id  nombre  apellido  ... dato 02     dato 03     dato 04
22  5217160  Harold  Metivier  ...    29.0  938.937514  779.415939
38  9328845  Trisha     Hague  ...   802.0  837.335328  752.771586
43  5018014  Thomas    Tongue  ...   145.0  976.394745  809.289486
45  4297762  Harold    Howard  ...   173.0  965.993949  751.407470

[4 rows x 9 columns]


In [ ]:
dato_02 = data[data["nombre"].str.contains("nn")]
print(dato_02)

         id   nombre  apellido  ... dato 02     dato 03     dato 04
0   4292166    Glenn  Hubertus  ...   666.0         NaN    8.348096
35  7033621  Annette      Simm  ...   856.0   14.003894  741.738159
37  9607843  Suzanne    Rincon  ...   661.0  551.448196  824.835620

[3 rows x 9 columns]


In [ ]:
data["dato 05"] = data["dato 03"]
print(data)

         id     nombre   apellido  ...     dato 03     dato 04     dato 05
0   4292166      Glenn   Hubertus  ...         NaN    8.348096         NaN
1   4660687      Jesse    Andrews  ...  531.908726         NaN  531.908726
2   2083836     Harold    Maulden  ...  634.372023  774.595716  634.372023
3   8070304    Darrick     Graham  ...  181.339371  419.969781  181.339371
4   2664601   Madeline      Corns  ...  405.608945         NaN  405.608945
5   2312309      James  Mcfarland  ...  275.142805  873.447967  275.142805
6   5090841        ???        NaN  ...  791.892719  475.066515  791.892719
7   5055108       Jeff      Piper  ...  327.593104  976.313296  327.593104
8   4222113        Max    Allegra  ...  268.400996  265.210264  268.400996
9   5428583       Mimi    Maxwell  ...  157.481774  426.939683  157.481774
10  1007469      Wanda       Burt  ...  709.203480  578.718582  709.203480
11  6497735    Crystal    Lavelle  ...  444.283423  866.470594  444.283423
12  2479885     Judith   

In [ ]:
data["dato 06"] = data["dato 03"] + data["dato 04"]
print(data)

         id     nombre   apellido  ...     dato 04     dato 05      dato 06
0   4292166      Glenn   Hubertus  ...    8.348096         NaN          NaN
1   4660687      Jesse    Andrews  ...         NaN  531.908726          NaN
2   2083836     Harold    Maulden  ...  774.595716  634.372023  1408.967738
3   8070304    Darrick     Graham  ...  419.969781  181.339371   601.309152
4   2664601   Madeline      Corns  ...         NaN  405.608945          NaN
5   2312309      James  Mcfarland  ...  873.447967  275.142805  1148.590773
6   5090841        ???        NaN  ...  475.066515  791.892719  1266.959234
7   5055108       Jeff      Piper  ...  976.313296  327.593104  1303.906400
8   4222113        Max    Allegra  ...  265.210264  268.400996   533.611260
9   5428583       Mimi    Maxwell  ...  426.939683  157.481774   584.421458
10  1007469      Wanda       Burt  ...  578.718582  709.203480  1287.922061
11  6497735    Crystal    Lavelle  ...  866.470594  444.283423  1310.754017
12  2479885 

In [ ]:
with pd.option_context('display.max_rows', None, 'display.max_columns', None):
  print(data)

         id     nombre   apellido       sexo fecha de nacimiento  dato 01  \
0   4292166      Glenn   Hubertus  masculino          1983-10-28    238.0   
1   4660687      Jesse    Andrews  masculino          1981-07-21     11.0   
2   2083836     Harold    Maulden  masculino          1981-07-24    585.0   
3   8070304    Darrick     Graham  masculino          1980-11-14      NaN   
4   2664601   Madeline      Corns   femenino                 NaN    835.0   
5   2312309      James  Mcfarland  masculino          1977-03-19    922.0   
6   5090841        ???        NaN  masculino          1978-05-11    633.0   
7   5055108       Jeff      Piper  masculino          1978-02-17    985.0   
8   4222113        Max    Allegra  masculino                 NaN    467.0   
9   5428583       Mimi    Maxwell   femenino          1985-05-04    546.0   
10  1007469      Wanda       Burt   femenino          1973-05-21      NaN   
11  6497735    Crystal    Lavelle   femenino          1979-08-27    421.0   

In [ ]:
print(data)

         id     nombre   apellido  ...     dato 04     dato 05      dato 06
0   4292166      Glenn   Hubertus  ...    8.348096         NaN          NaN
1   4660687      Jesse    Andrews  ...         NaN  531.908726          NaN
2   2083836     Harold    Maulden  ...  774.595716  634.372023  1408.967738
3   8070304    Darrick     Graham  ...  419.969781  181.339371   601.309152
4   2664601   Madeline      Corns  ...         NaN  405.608945          NaN
5   2312309      James  Mcfarland  ...  873.447967  275.142805  1148.590773
6   5090841        ???        NaN  ...  475.066515  791.892719  1266.959234
7   5055108       Jeff      Piper  ...  976.313296  327.593104  1303.906400
8   4222113        Max    Allegra  ...  265.210264  268.400996   533.611260
9   5428583       Mimi    Maxwell  ...  426.939683  157.481774   584.421458
10  1007469      Wanda       Burt  ...  578.718582  709.203480  1287.922061
11  6497735    Crystal    Lavelle  ...  866.470594  444.283423  1310.754017
12  2479885 