<a href="https://colab.research.google.com/github/devjaime/data_science_escalab/blob/main/Copia_de_2021_11_11_Clase_03_02.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NumPy

NUMerical PYthon
*   Potente estructura de datos
*   Implementa matrices y matrices multidimensionales
*   Estas estructuras garantizan cálculos eficientes con matrices

Sintaxis de Numpy

import numpy as np
*   matriz_1 = np.array([1,2,3])
*   matriz_2 = np.array([1,2,3], [4,5,6])



In [ ]:
import numpy as np

In [ ]:
matriz = np.array([1,2,3])
print(matriz)

[1 2 3]


## Creación de arreglos

In [ ]:
matriz_1d = np.array([1,2,3])
print(matriz_1d)

[1 2 3]


In [ ]:
mi_lista = [1, 2, 3, 4, 5]
mi_arreglo = np.array([1, 2, 3, 4, 5])

print(mi_lista, type(mi_lista))
print(mi_arreglo, type(mi_arreglo))

[1, 2, 3, 4, 5] <class 'list'>
[1 2 3 4 5] <class 'numpy.ndarray'>


In [ ]:
# multiplicación o división por escalar
print(mi_lista * 2)
print(mi_arreglo * 2)

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]
[ 2  4  6  8 10]


In [ ]:
for i in mi_lista:
  print(i*2, end=" ")

2 4 6 8 10 

In [ ]:
# suma o resta con escalar
# print(mi_lista + 10) # ups!
print(mi_arreglo + 10)

[11 12 13 14 15]


In [ ]:
# suma o resta entre "vectores" 
print(mi_lista + mi_lista)
print(mi_arreglo + mi_arreglo)

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]
[ 2  4  6  8 10]


In [ ]:
# comparación
# print(mi_lista < 4) # ups!
print(mi_arreglo < 4)

[ True  True  True False False]


In [ ]:
matriz_1d = np.array([1,2,3])
print(matriz_1d)

[1 2 3]


In [ ]:
matriz_2d = np.array([[1,2,3],[4,5,6]])
print(matriz_2d)

[[1 2 3]
 [4 5 6]]


In [ ]:
matriz_3d = np.array([      [  [1, 2], [3, 4]  ], [  [5, 6], [7, 8]   ]      ])
print(matriz_3d)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


NumPy ocupa menos espacio en memoria y es más rápido

In [ ]:
import sys
lista_python = l = [i for i in range(1000)]
print(sys.getsizeof(lista_python))
print(sys.getsizeof(0)*len(lista_python))

9032
24000


In [ ]:
print(lista_python)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194, 195, 196, 197, 198, 199, 200, 201, 202, 203, 204, 205, 206, 207, 208, 209, 210, 211, 212, 213, 214, 215, 216, 217, 218, 219, 220, 221,

In [ ]:
lista_np = np.arange(1000)
print(sys.getsizeof(lista_np))
print(lista_np.size*lista_np.itemsize)

8096
8000


In [ ]:
print(lista_np)

[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35
  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53
  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71
  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89
  90  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107
 108 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125
 126 127 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143
 144 145 146 147 148 149 150 151 152 153 154 155 156 157 158 159 160 161
 162 163 164 165 166 167 168 169 170 171 172 173 174 175 176 177 178 179
 180 181 182 183 184 185 186 187 188 189 190 191 192 193 194 195 196 197
 198 199 200 201 202 203 204 205 206 207 208 209 210 211 212 213 214 215
 216 217 218 219 220 221 222 223 224 225 226 227 228 229 230 231 232 233
 234 235 236 237 238 239 240 241 242 243 244 245 24

In [ ]:
# tiempo
import time
tamano = 1000000
lp_1 = range(tamano)
lp_2 = range(tamano)
ln_1 = np.arange(tamano)
ln_2 = np.arange(tamano)

inicio = time.time()
resultado = [x+y for  x,y in zip(lp_1,lp_2)]
print("resultado en python")
print(time.time()-inicio)

print()

inicio = time.time()
resultado = ln_1+ln_2
print("resultado en numpy")
print(time.time()-inicio)

resultado en python
0.1281278133392334

resultado en numpy
0.016499042510986328


In [ ]:
# especificar el tipo de dato
array_01 = np.array([[1,2,3,4],[5,6,7,8]], dtype=np.int64)
print(array_01)

[[1 2 3 4]
 [5 6 7 8]]


In [ ]:
# especificar matrices vacías o con datos específicos (filas, columnas)
unos = np.ones([3,4])
print(unos)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [ ]:
ceros = np.zeros([3,4])
print(ceros)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [ ]:
aleatorios = np.random.random([3,4])
print(aleatorios)

[[0.13577459 0.17823088 0.97100375 0.45423678]
 [0.22272216 0.99345636 0.69581039 0.91074193]
 [0.70592263 0.29420447 0.40062676 0.41127963]]


In [ ]:
vacia = np.empty((3,4))
print(vacia)

[[0.00000000e+000 4.65636175e-310 3.95252517e-323 4.65636175e-310]
 [3.95252517e-323 4.65636175e-310 4.44659081e-323 0.00000000e+000]
 [4.65636175e-310 4.65636175e-310 4.65636175e-310 0.00000000e+000]]


In [ ]:
full = np.full((3,4), 8)
print(full)

[[8 8 8 8]
 [8 8 8 8]
 [8 8 8 8]]


In [ ]:
# matriz con valores espaciados uniformemente
espacio1 = np.arange(0,30,5)
print(espacio1)

espacio2 = np.linspace(0,2,5)
print(espacio2)

[ 0  5 10 15 20 25]
[0.  0.5 1.  1.5 2. ]


In [ ]:
# matriz identidad
identidad1 = np.eye(5,4)
print(identidad1)

print()

identidad2 = np.identity(4)
print(identidad2)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [0. 0. 0. 0.]]

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
# desde un iterable
arreglo = np.array(range(4))
print(arreglo)

[0 1 2 3]


In [ ]:
# desde una lista de listas con dtype?

arreglo = np.array([[1,2,3], [4,5,6]], dtype=float)
print(arreglo)
print(arreglo.shape)
print(arreglo.dtype)



[[1. 2. 3.]
 [4. 5. 6.]]
(2, 3)
float64


In [ ]:
# ejemplo
lista = [1,2,9]
print(lista)
lista[2] = lista[2]/2
print(lista)

[1, 2, 9]
[1, 2, 4.5]


9

In [ ]:
# y si una operación "cambia" el tipo de mi arreglo?
arreglo = np.array([1,2,9])
arreglo[2] = arreglo[2]/2
print(arreglo)

[1 2 4]


In [ ]:
# y si una operación "cambia" el tipo de mi arreglo?
arreglo = np.array([1,2,9])
print(arreglo)
arreglo = arreglo.astype('float64')
print(arreglo)
arreglo[2] = arreglo[2]/2
print(arreglo)


[1 2 9]
[1. 2. 9.]
[1.  2.  4.5]


## Constantes

In [ ]:

# https://numpy.org/doc/stable/reference/constants.html
print(np.inf)
print()
print(np.NINF)
print()
print(np.PINF)
print()
print(np.nan)
print()

In [ ]:
valor = np.nan
numero = 10
print(numero < valor)
print(numero > valor)
print(numero == valor)

False
False
False


In [ ]:
valor = np.inf
numero = 67888888888888888
print(numero < valor)
print(numero > valor)
print(numero == valor)

True
False
False


# Utilidades en Numpy

In [ ]:
# conocer las dimensiones de una matriz
a = np.array([[1,2,3],[4,5,6]])
print(a.ndim)


2


In [ ]:
# conocer el tipo de datos
print(a.dtype)

int64


In [ ]:
# tamaño y forma de la matriz
print(a.size)
print(a.shape)
print()
print(len(a))

6
(2, 3)

2


In [ ]:
print(a)

[[1 2 3]
 [4 5 6]]


In [ ]:
# cambio de forma de una matriz
b = a.reshape(1,6)
print(b)
print(b.shape)
b = b.reshape(6)
print(b.shape)

[[1 2 3 4 5 6]]
(1, 6)
(6,)


In [ ]:
# crear y modificar
arreglo = np.arange(27)
print(arreglo)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26]


In [ ]:
# crear y modificar
arreglo = np.arange(27).reshape((3,3,3))
print(arreglo)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


In [ ]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
# extraer un número de la matriz [fila, columna]
print(a[0,2])

3


In [ ]:
# extraer varios números de la matriz [fila, columna]
print(a)
print()
print(a[:,2])
print()
print(a[0,:])

[[1 2 3]
 [4 5 6]]

[3 6]

[1 2 3]


In [ ]:
# operaciones matemáticas
c = np.array([2,8,4,3,4,5,6,1,2,3,5])
print(c.min())
print(c.max())
print(c.sum())
print(c.cumsum())

1
8
43
[ 2 10 14 17 21 26 32 33 35 38 43]


In [ ]:
print(a)
print()
print(a.min())
print(a.max())
print(a.sum())

[[1 2 3]
 [4 5 6]]

1
6
21


In [ ]:
# raíz cuadrada, media, mediana y desviación estandar
print(np.sqrt(a))
print()
print(np.mean(a))
print()
print(np.median(a))
print()
print(np.std(a))

[[1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974]]

3.5

3.5

1.707825127659933


In [ ]:
# en python no!
lista_a = [[1,2,3],[4,5,6]]
lista_b = [[4,5,6],[7,8,9]]
print(lista_a+lista_b)

[[1, 2, 3], [4, 5, 6], [4, 5, 6], [7, 8, 9]]


In [ ]:
x = np.array([[1,2,3],[4,5,6]])
y = np.array([[1,2,3],[4,5,6]])
print(x+y)
print(x-y)
print(x*y)
print(x/y)

[[ 2  4  6]
 [ 8 10 12]]
[[0 0 0]
 [0 0 0]]
[[ 1  4  9]
 [16 25 36]]
[[1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
# añadir y eliminar elementos
a = np.array([1,2,3])
a = np.append(a,(4,5))

print(a)



[1 2 3 4 5]


In [ ]:
# añadir y eliminar elementos
a = np.array([81,28,37])
print(a)
a = np.delete(a,1)
print(a)

[81 28 37]
[81 37]


In [ ]:
# buscar en arreglo 1d
a = np.array([1,2,3,4,5,6])
print(a)
x = np.where(a == 4)
print(x)

[1 2 3 4 5 6]
(array([3]),)


In [ ]:
lista = [1,2,3,4,5,7,4,9]
x = 0
contador=0
for x in range(len(lista)):
  x = lista[contador]
  if x == 4:
    print(contador)
  contador += 1

print()
print()
print(4 in lista)
index = lista.index(4)
print(index)


3
6


True
3


In [ ]:
# buscar en arreglo 2d
a = np.array([[1,2,3],[4,5,6]])
print(a)
x = np.where(a == 4)
print(x)

[[1 2 3]
 [4 5 6]]
(array([1]), array([0]))


In [ ]:
# ordenar
a = np.array([4,5,7,1,3,2])
print(a)
a = np.sort(a)
print(a)

[4 5 7 1 3 2]
[1 2 3 4 5 7]


In [ ]:
lista_ = [1,2,3]
lista__ = [4,5,6]
lista___ = [4,5,8]
print(lista_)
print(lista__)
print(lista___)

[1, 2, 3]
[4, 5, 6]
[4, 5, 8]


In [ ]:
# ordenar
a = np.array([[4,7,5],[1,3,2],[8,1,3],[7,4,9]])
print(a)
print()
x = np.msort(a)
print(x)

[[4 7 5]
 [1 3 2]
 [8 1 3]
 [7 4 9]]

[[1 1 2]
 [4 3 3]
 [7 4 5]
 [8 7 9]]


# Iteraciones

In [ ]:
a

array([[4, 7, 5],
       [1, 3, 2],
       [8, 1, 3],
       [7, 4, 9]])

In [ ]:
for elemento in a:
  for sub_elemento in elemento:
    print(sub_elemento, end=" ")

4 7 5 1 3 2 8 1 3 7 4 9 

In [ ]:
# a = np.arange(6).reshape(2,3)
print(a)
for x in np.nditer(a):
    print(x, end=' ')

[[4 7 5]
 [1 3 2]
 [8 1 3]
 [7 4 9]]
4 7 5 1 3 2 8 1 3 7 4 9 

In [ ]:
# a = np.arange(6).reshape(2,3)
print(a)
for x in np.nditer(a, order='C'):
    print(x, end=' ')

[[4 7 5]
 [1 3 2]
 [8 1 3]
 [7 4 9]]
4 7 5 1 3 2 8 1 3 7 4 9 

In [ ]:
# a = np.arange(6).reshape(2,3)
print(a)
for x in np.nditer(a, order='F'):
    print(x, end=' ')

[[4 7 5]
 [1 3 2]
 [8 1 3]
 [7 4 9]]
4 1 8 7 7 3 1 4 5 2 3 9 